### ISSUE TITLE
(Hospital views student) Tabelle mit den restlichen spalten erweitern

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#20] opened 2020-03-23 20:32 UTC
https://pypi.org/project/django-advanced-filters/

https://hackernoon.com/how-to-add-tags-to-your-models-in-django-django-packages-series-1-4y1b32sf

https://getbootstrap.com/docs/4.4/components/badge/

**Comment by maltezacharias** [comment] 2020-03-25 18:30
Possible duplicate of #32 ?

**Comment by josauder** [comment] 2020-03-26 12:01
this issue is obsolete with new table

**Closed by josauder** 2020-03-26 12:01 UTC
Labels: question
