### ISSUE TITLE
Setup Mail service

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#4] opened 2020-03-23 18:06 UTC
A privately hosted mail server will probably be classified as spam by Gmail etc.

- [x] Find a mail service which we can use
- [x] Add configuration to settings/production.py **only on production server**

**Comment by Baschdl** [comment] 2020-03-24 22:14
We will probably use sendgrid and see how far we can go with them

**Comment by maltezacharias** [comment] 2020-03-25 18:35
duplicate of #49 or obsolete @Baschdl ?

**Comment by josauder** [comment] 2020-03-27 20:50
@Baschdl Is this still an issue? If not, please close

**Closed** 2020-03-27 21:09 UTC
Labels: duplicate, question
